import {MigrationInterface, QueryRunner} from "typeorm";

export class script11656517034074 implements MigrationInterface {
    name = 'script11656517034074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "countryId" character varying(10), "countryName" character varying(50), "stateId" character varying(10), "stateName" character varying(50), "cityId" character varying(10), "cityName" character varying(50), "addressDetails" character varying(50), CONSTRAINT "PK_9034683839599c80ebe9ebb0891" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "profileName" character varying(50) NOT NULL, "firstName" character varying(50) NOT NULL, "lastName" character varying(50) NOT NULL, "contactNumber" character varying(100), "addressId" uuid, CONSTRAINT "REL_82e9573eb65966504b27754065" UNIQUE ("addressId"), CONSTRAINT "PK_89dff233f744d59758158aca1d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "userName" character varying(50) NOT NULL, "password" character varying(50), "profileId" uuid, CONSTRAINT "UQ_2db873448f830f8ed7f6ce19474" UNIQUE ("userName"), CONSTRAINT "REL_2041c7acbba08abd3a5073d6f4" UNIQUE ("profileId"), CONSTRAINT "PK_bf68fd30f1adeede9c72a5cac09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "City" ("id" character varying NOT NULL, "name" character varying(200) NOT NULL, "stateCode" character varying(10) NOT NULL, "stateName" character varying(200) NOT NULL, "countryId" character varying(10) NOT NULL, "countryCode" character varying(10) NOT NULL, "countryName" character varying(50) NOT NULL, "latitude" numeric NOT NULL, "longitude" numeric NOT NULL, "wikiDataId" character varying(50), "isActive" character varying NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL DEFAULT 'system', "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL DEFAULT 'system', "internalComment" character varying(300), "stateId" character varying, CONSTRAINT "PK_1c5a287828771160a6e703cd37e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "State" ("id" character varying NOT NULL, "name" character varying(200) NOT NULL, "countryCode" character varying(10) NOT NULL, "countryName" character varying(50) NOT NULL, "stateCode" character varying(10), "type" character varying(100), "latitude" numeric, "longitude" numeric, "isActive" character varying NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL DEFAULT 'system', "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL DEFAULT 'system', "internalComment" character varying(300), "countryId" character varying, CONSTRAINT "PK_ba7801fef9aabc0a35a0110c896" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Country" ("id" character varying NOT NULL, "name" character varying(300), "iso3" character varying(10), "iso2" character varying(10), "numericCode" character varying(10), "phoneCode" character varying(50), "capital" character varying(50), "currency" character varying(10), "currencyName" character varying(50), "currencySymbol" character varying(10), "tld" character varying(10), "native" character varying(50), "region" character varying(50), "subRegion" character varying(50), "timeZone" character varying(5000), "latitude" numeric NOT NULL, "longitude" numeric NOT NULL, "isActive" character varying NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL DEFAULT 'system', "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL DEFAULT 'system', "internalComment" character varying(300), CONSTRAINT "PK_43cb4419fc372b859dec2618037" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Organizer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "userId" character varying NOT NULL, "eventId" uuid, CONSTRAINT "PK_2bbc86c58221b2fdfe632138372" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "tag" character varying NOT NULL, CONSTRAINT "PK_61aa7408a426fea5dd8416f5a12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Event_eventtype_enum" AS ENUM('Virtual', 'Non-Virtual')`);
        await queryRunner.query(`CREATE TABLE "Event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "eventType" "public"."Event_eventtype_enum" NOT NULL DEFAULT 'Virtual', "eventName" character varying NOT NULL, "link" character varying, "location" character varying, "timeZone" character varying NOT NULL, "startDate" date NOT NULL, "startTime" TIME NOT NULL, "endDate" date NOT NULL, "endTime" TIME NOT NULL, "description" character varying, "showContactNumbers" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_894abf6d0c8562b398c717414d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "createDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" character varying(300) NOT NULL, "lastChangedDateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastChangedBy" character varying(300) NOT NULL, "internalComment" character varying(300), "roleName" character varying(50) NOT NULL, CONSTRAINT "PK_9309532197a7397548e341e5536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Timezone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "abbreviation" character varying NOT NULL, "timeZone" character varying NOT NULL, "UTCoffset" character varying NOT NULL, "GMToffset" character varying NOT NULL, CONSTRAINT "PK_1e05a6436d98c6a558f53b8856d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event_tags_tags" ("eventId" uuid NOT NULL, "tagsId" uuid NOT NULL, CONSTRAINT "PK_e425d9fe4ed295b0a2bf84cf73e" PRIMARY KEY ("eventId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79ac4f881a986ed68677cf6426" ON "event_tags_tags" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_69ee1b09b58425f3a310e4f3e4" ON "event_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "role_account_account" ("roleId" uuid NOT NULL, "accountId" uuid NOT NULL, CONSTRAINT "PK_98d92acc3c992ebda2e7aaaf10b" PRIMARY KEY ("roleId", "accountId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de689312e4accdee8f6a9ac078" ON "role_account_account" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_19d77f4a7b78f39eb874c6e715" ON "role_account_account" ("accountId") `);
        await queryRunner.query(`ALTER TABLE "Profile" ADD CONSTRAINT "FK_82e9573eb65966504b27754065d" FOREIGN KEY ("addressId") REFERENCES "Address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Account" ADD CONSTRAINT "FK_2041c7acbba08abd3a5073d6f4a" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "City" ADD CONSTRAINT "FK_36fb0a41ca1b746c06c999c5aff" FOREIGN KEY ("stateId") REFERENCES "State"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "State" ADD CONSTRAINT "FK_29e59f09a2f061d8252c82cea7e" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Organizer" ADD CONSTRAINT "FK_33a2b485eb08db307d535f2d0a9" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_tags_tags" ADD CONSTRAINT "FK_79ac4f881a986ed68677cf6426d" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event_tags_tags" ADD CONSTRAINT "FK_69ee1b09b58425f3a310e4f3e4c" FOREIGN KEY ("tagsId") REFERENCES "Tags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_account_account" ADD CONSTRAINT "FK_de689312e4accdee8f6a9ac0784" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_account_account" ADD CONSTRAINT "FK_19d77f4a7b78f39eb874c6e7150" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_account_account" DROP CONSTRAINT "FK_19d77f4a7b78f39eb874c6e7150"`);
        await queryRunner.query(`ALTER TABLE "role_account_account" DROP CONSTRAINT "FK_de689312e4accdee8f6a9ac0784"`);
        await queryRunner.query(`ALTER TABLE "event_tags_tags" DROP CONSTRAINT "FK_69ee1b09b58425f3a310e4f3e4c"`);
        await queryRunner.query(`ALTER TABLE "event_tags_tags" DROP CONSTRAINT "FK_79ac4f881a986ed68677cf6426d"`);
        await queryRunner.query(`ALTER TABLE "Organizer" DROP CONSTRAINT "FK_33a2b485eb08db307d535f2d0a9"`);
        await queryRunner.query(`ALTER TABLE "State" DROP CONSTRAINT "FK_29e59f09a2f061d8252c82cea7e"`);
        await queryRunner.query(`ALTER TABLE "City" DROP CONSTRAINT "FK_36fb0a41ca1b746c06c999c5aff"`);
        await queryRunner.query(`ALTER TABLE "Account" DROP CONSTRAINT "FK_2041c7acbba08abd3a5073d6f4a"`);
        await queryRunner.query(`ALTER TABLE "Profile" DROP CONSTRAINT "FK_82e9573eb65966504b27754065d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19d77f4a7b78f39eb874c6e715"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de689312e4accdee8f6a9ac078"`);
        await queryRunner.query(`DROP TABLE "role_account_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69ee1b09b58425f3a310e4f3e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79ac4f881a986ed68677cf6426"`);
        await queryRunner.query(`DROP TABLE "event_tags_tags"`);
        await queryRunner.query(`DROP TABLE "Timezone"`);
        await queryRunner.query(`DROP TABLE "Role"`);
        await queryRunner.query(`DROP TABLE "Event"`);
        await queryRunner.query(`DROP TYPE "public"."Event_eventtype_enum"`);
        await queryRunner.query(`DROP TABLE "Tags"`);
        await queryRunner.query(`DROP TABLE "Organizer"`);
        await queryRunner.query(`DROP TABLE "Country"`);
        await queryRunner.query(`DROP TABLE "State"`);
        await queryRunner.query(`DROP TABLE "City"`);
        await queryRunner.query(`DROP TABLE "Account"`);
        await queryRunner.query(`DROP TABLE "Profile"`);
        await queryRunner.query(`DROP TABLE "Address"`);
    }

}
